name: makeusers
recipe: lamp
config:
    webroot: public
services:
  appserver:
    portforward: 3307
tooling:
    require:
        service: appserver
        description: This command install the require packages from the user through lando into the container
        cmd: /app/scripts/composerInternal.sh
